apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    generation: 1
    labels:
      build: micro-couchbase
    name: micro-couchbase
    namespace: fbac
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    labels:
      build: micro-couchbase
    name: micro-couchbase
    namespace: fbac
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'micro-couchbase:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers:
      - github:
          secret: uLN-Dfqt-Pjr4_ToVChC
        type: GitHub
      - generic:
          secret: '-Gx-cUZTQBDtgkAuPRGE'
        type: Generic
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "micro-couchbase", "namespace": "fbac", "kind": "DeploymentConfig"}]'
    name: micro-couchbase-service-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/bobbydeveaux/micro-couchbase.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ./Jenkinsfile
    triggers:
    - generic:
        secret: RandomPassword123
      type: Generic 
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 3
    labels:
      app: couchbase-server
    name: couchbase-server
    namespace: fbac
  spec:
    replicas: 1
    selector:
      app: couchbase-server
      deploymentconfig: couchbase-server
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mcouchbase-server
          deploymentconfig: couchbase-server
      spec:
        containers:
          - env:
              - name: TYPE
                value: 'MASTER'
            imagePullPolicy: Always
            name: micro-couchbase
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: false
          containerNames:
            - micro-couchbase
          from:
            kind: ImageStreamTag
            name: 'micro-couchbase:latest'
            namespace: fbac
        type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 3
    labels:
      app: couchbase-worker
    name: couchbase-worker
    namespace: fbac
  spec:
    replicas: 1
    selector:
      app: couchbase-worker
      deploymentconfig: couchbase-worker
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mcouchbase-worker
          deploymentconfig: couchbase-worker
      spec:
        containers:
          - env:
              - name: TYPE
                value: 'WORKER'
              - name: COUCHBASE_MASTER
                value: 'couchbase-server'
            imagePullPolicy: Always
            name: micro-couchbase
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: false
          containerNames:
            - micro-couchbase
          from:
            kind: ImageStreamTag
            name: 'micro-couchbase:latest'
            namespace: fbac
        type: ImageChange